version: '3.2'

services:

  broker:
    container_name: "rabbit"
    image: rabbit_image
    restart: always
    ports:
      - 1883:1883
      - 5672:5672
      - 15672:15672
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    environment:
            - "RABBITMQ_DEFAULT_PASS=pass"
            - "RABBITMQ_DEFAULT_USER=user"
    networks:
      default:
        aliases:
          - rabbit

  #----------------------------------------------

  database:
    container_name: "influx"
    image: influx_image
    restart: always
    ports:
      - 8086:8086
    build:
      context: .
      dockerfile: influx/Dockerfile
    networks:
      default:
        aliases:
          - influx
          
  #----------------------------------------------

  comucacion:
    container_name: "telegraf"
    image: telegraf_image
    restart: always
  
    build:
      context: .
      dockerfile: telegraf/Dockerfile
    environment:
      - INFLUX_TOKEN=Xlk25GXe32sWWJ9NnOdNEVOg4kRRK0xK80dfK8McI_moe4EVl5MVzUOI5jLhv4I4-seZInhcd86F3UBO6JrsPA==
    command: --config http://influx:8086/api/v2/telegrafs/0aaad8aaafc99000
    networks:
      default:
        aliases:
          - telegraf
    depends_on:
      - database

  gui:
    container_name: grafana
    image: grafana-image
    restart: always
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: grafana/Dockerfile
    depends_on:
      - database
  
          


    
